### ISSUE TITLE
New Embed Feature Not Working

### ISSUE THREAD

**Issue by Snnackss** [Hubro/clipface#12]
I pulled latest from Docker and I cannot get the embed to work. At first I thought it was because my local DNS may have been messing it up, so I swapped my DNS and it still won't load. I tried a brand new clip as well and it didn't work, but as I am typing this I just noticed something. Above the clip name it shows the IP it is trying to connect to and that IP is 127.0.0.1:2095 which is the IP and port my NGINX reverse proxy is pointing towards.

https://imgur.com/a/jHO4day

**Comment by Hubro** [comment]
Ah yes, I forgot to mention, take a look at the updated NGINX example configuration. You need to forward the scheme and hostname to the Clipface server.

**Comment by Snnackss** [comment]
Okay, I have done this, but I cannot seem to get it to recognize the port I need to to connect to. On Discord where it once said 127.0.0.1:2095 it now says "snnacks.tv", but not "snnacks.tv:2096" which is the port the reverse proxy is open on.

https://imgur.com/a/mulaJBE

**Comment by Hubro** [comment]
> Okay, I have done this, but I cannot seem to get it to recognize the port I need to to connect to. On Discord where it once said 127.0.0.1:2095 it now says "snnacks.tv", but not "snnacks.tv:2096" which is the port the reverse proxy is open on.
> 
> https://imgur.com/a/mulaJBE

Oh, it didn't occur to me anybody would use a non-standard port, so I haven't kept that in mind. You'll probably need to forward another header from NGINX, and I'll need to make a couple of changes.

**Comment by Hubro** [comment]
Strange, I just tested this and it seems to work for me:

```bash
curl -s \
    -H "Cookie: auth=%242b%2410%24rdN4PCOO6KQ5ENosXPe8qOD92VRyKjWGFexsySvwPV44lUINai2I6" \
    -H "X-Forwarded-Proto: https" \
    -H "X-Forwarded-Host: clipface-host.com:8080" \
    "http://localhost:3000/watch/example-clip.mkv"
```

This produces this URL in the OpenGraph meta tags:

```
https://clipface-host.com:8080/api/video/example-clip.mkv
```

Can you confirm that you have reloaded your NGINX config after your latest changes?

**Comment by Snnackss** [comment]
Okay, so it eventually solved itself, I guess nginx just wasn't updating. The other issue I had was constant spinning in the embed box and when an embed would load in Discord, it would literally max out my pathetic 5Mbps connection even with smart queues enable in my router. So, I decided to say screw it and I am renting a VPS from VULTR until SpaceX gets Starlink and it's stable in half a year+.

Thanks man. I seriously appreciate your help and effort in creating this. I had an idea/suggestion about adding an "upload" option directly on the website dashboard locked behind authentication (I was using samba to send files via network storage on Windows, but not I'm using FTP now since I have a VPS so the idea just came across my mind that's all). If it's something you think could be cool to add, that'd be awesome, but I don't want to make another "issue" or whatever on github or bug you anymore about my silly ideas/issues than I have already. Again, thank you so much.

**Comment by Hubro** [comment]
> Okay, so it eventually solved itself, I guess nginx just wasn't updating. The other issue I had was constant spinning in the embed box and when an embed would load in Discord, it would literally max out my pathetic 5Mbps connection even with smart queues enable in my router. So, I decided to say screw it and I am renting a VPS from VULTR until SpaceX gets Starlink and it's stable in half a year+.

Cool :slightly_smiling_face: 

> Thanks man. I seriously appreciate your help and effort in creating this. I had an idea/suggestion about adding an "upload" option directly on the website dashboard locked behind authentication (I was using samba to send files via network storage on Windows, but not I'm using FTP now since I have a VPS so the idea just came across my mind that's all). If it's something you think could be cool to add, that'd be awesome, but I don't want to make another "issue" or whatever on github or bug you anymore about my silly ideas/issues than I have already. Again, thank you so much.

Already planned :) https://github.com/Hubro/clipface/issues/2
