### ISSUE TITLE
Authentication is not working

### ISSUE THREAD

**Issue by yolanv** [Hubro/clipface#37]
I'm using the Docker image to install your application. I'm also running the clipface application behind a reverse proxy with SSL enabled and using letsencrypt certification. I've tried setting secure_cookies to false but that did not help either.

Problem:
When setting a password through the environment variable `CLIPFACE_USER_PASSWORD`, the page becomes password-protected but I am not able to log in with the set password. I've tried many passwords (including password123 from the example). It just tells me the password is wrong.

**Comment by Hubro** [comment]
Do you see any errors in the logs? (`docker logs [CLIPFACE_CONTAINER_NAME]`)

If you open the developer tools (F12 in Chrome) and go to the "Console" tab, do you see any errors in there when you try to log in?

**Comment by tomzorz** [comment]
I'm experiencing the same thing... except I don't get any error messages - the login button turns into an animating cogwheel and nothing happens.

When I hit enter, the `/login` endpoint returns OK, but the last request seems to be the issue:

![image](https://user-images.githubusercontent.com/6363312/132349031-4557407e-39de-46bb-9165-b391c276c1ea.png)

Response from index.json

![image](https://user-images.githubusercontent.com/6363312/132349116-b0395f7b-0f2a-471a-9206-126da07461f0.png)

No response afterwards

![image](https://user-images.githubusercontent.com/6363312/132349155-7a1b15a8-5016-4bc9-9e03-d4f24819e212.png)

**Comment by Hubro** [comment]
@tomzorz Any messages in the server log? (`docker logs my-clipface-container`)

Can you show me the "Headers" tab for the "login" request in your last screenshot? (6th request from the bottom)

**Comment by tomzorz** [comment]
Mmmm totally my bad, I forgot to set up the secure_cookie var to false - it works now!
