### ISSUE TITLE
Copy link / copy public link buttons don't work

### ISSUE THREAD

**Issue by tomzorz** [Hubro/clipface#38]
Whenever I press either of the buttons I get a "failed to copy link" javascript error.

The `/create-single-clip-token` network call succeeds, and returns a json object with a token key/value. But I see a js error in the console:

![image](https://user-images.githubusercontent.com/6363312/132419007-1e7245ae-5067-447e-9e95-b0905f1fd212.png)

**Comment by Hubro** [comment]
Seems like your browser doesn't support the clipboard API. Which browser are you using?

https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText

**Comment by tomzorz** [comment]
Vivaldi 4.1.2369.21 (Stable channel) (64-bit) - latest chromium for all intents and purposes. 

According to the table at the link and this test site https://async-clipboard-api.glitch.me it works.

**Comment by Hubro** [comment]
Weird. This is the code that fails in your case:

```javascript
try {
  await navigator.clipboard.writeText(clipURL.href);
  setLinkCopied(true);
} catch (e) {
  console.error(e);
  alert("Failed to copy link!");
}
```

Not really much room for bugs here, and it works for me. I also use Vivaldi as my daily driver.

I don't see any other alternative than there being a permission issue in your browser. Could it have something to do with HTTPS? Perhaps Clipboard API access is only granted by default on secure sites?

**Comment by tomzorz** [comment]
Eyyyy, it was HTTPS apparently, good hunch. This comment was helpful in the end https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined#comment115247674_51823007 apparently I can add an exception for it in `vivaldi://flags` and boom suddenly it works. :) 

PS: 🧡 for Vivaldi

**Comment by Hubro** [comment]
> PS: 🧡 for Vivaldi

Hell yes!

Glad it worked out 😄

**Comment by tomzorz** [comment]
Btw, this is not the first "self-hosted streamable" alternative I've been trying, and a different one had an interesting alternative security concept: you could set a subnet (e.g. 192.168.0.0/16) from which all requests are treated as admin, and then any public access from external IPs were only allowed to look at clip deep-links.
