### ISSUE TITLE
Authentication not working

### ISSUE THREAD

**Issue by VictorBrek** [Hubro/clipface#49]
After reviewing #37 it seems I have a similar but not solvable in the same way situation. when attempting to log in, the website hangs, and then after refreshing and trying again, it redirects to a blank webpage with the text
`{"__N_SSP":true,"pageProps":{"__N_REDIRECT":"/login?next=%2F_next%2Fdata%2FKQ6EOlWR4ZVZDVRR4cJF3%2Findex.json","__N_REDIRECT_STATUS":307}}`  and does not continue. 

`local.toml`:
```
user_password = "12345"
secure_cookies = false
```

`docker logs clipface` output:
```
$ next start -p 80
ready - started server on 0.0.0.0:80, url: http://localhost:80
Local settings set to { theaterMode: false, videoVolume: 1, clipsPerPage: 40 }
Local settings set to { theaterMode: false, videoVolume: 1, clipsPerPage: 40 }
User logged in successfully
Local settings set to { theaterMode: false, videoVolume: 1, clipsPerPage: 40 }
Local settings set to { theaterMode: false, videoVolume: 1, clipsPerPage: 40 }
Local settings set to { theaterMode: false, videoVolume: 1, clipsPerPage: 40 }
User logged in successfully
Local settings set to { theaterMode: false, videoVolume: 1, clipsPerPage: 40 }
Local settings set to { theaterMode: false, videoVolume: 1, clipsPerPage: 40 }
Local settings set to { theaterMode: false, videoVolume: 1, clipsPerPage: 40 }
User logged in successfully
Local settings set to { theaterMode: false, videoVolume: 1, clipsPerPage: 40 }
Local settings set to { theaterMode: false, videoVolume: 1, clipsPerPage: 40 }
Local settings set to { theaterMode: false, videoVolume: 1, clipsPerPage: 40 }
User logged in successfully
Local settings set to { theaterMode: false, videoVolume: 1, clipsPerPage: 40 }
```

Please let me know if I can help by supplying any more information

**Comment by VictorBrek** [comment]
After just using environment variables to adjust secure_cookies, it works now

**Comment by Hubro** [comment]
That's strange, your original config should also have worked. Are you sure you mapped `local.toml` to `/config/local.toml` inside the container?

**Comment by VictorBrek** [comment]
I am 100% sure the `local.toml` was located in `/config/local.toml` alongside `default.toml`

**Comment by VictorBrek** [comment]
also, side note, how would I change what port is used for the webserver, adjusting the -p 80:80 doesnt seem to be changing anythin?
