### ISSUE TITLE
Blank Playblack

### ISSUE THREAD

**Issue by sashi** [Hubro/clipface#52]
Hi all
I couldn't find an issue with mine but I have the docker container setup and everything looks good however when playing back videos the video is blank but the audio works fine

**Comment by Hubro** [comment]
All Clipface does is expose the video to the browser through a HTML5 `<video>` element. It sounds like your browser is unable to play your video.

For maximum compatibility, ensure that you are using the H264 codec and preferably the MP4 container. I have experienced the exact scenario you're describing when I tried using H265 (HEVC), and my browser was not able to play it.
