### ISSUE TITLE
Buffering in firefox.

### ISSUE THREAD

**Issue by hammyexe** [Hubro/clipface#57]
When I playback a video on the firefox browser, there is buffering.

**Comment by Hubro** [comment]
All Clipface does is expose the video recording to the browser through a HTML5 video element. Clipface has no role in actually playing the video, so which browser you are using shouldn't matter.

Do clips play smoothly in other browsers?

**Comment by hammyexe** [comment]
yes, it does play smoothly on other browsers.

**Comment by Hubro** [comment]
I can't replicate your issue. I tried playing back some very high resolution 120fps clips on Firefox and it plays perfectly. I'm guessing there's an issue with Firefox on your side, perhaps you are using a video codec that your install of Firefox can't hardware accelerate.

**Comment by hammyexe** [comment]
I'll look to see if its an addon.
